const express = require("express")
const ctrls = require("../controllers/userController")
const { verifyAccessToken, isAdmin } = require("../middlewares/verifyToken")
const uploader = require("../config/cloudinary.config")
const router = express.Router()

router.post('/register', ctrls.register)
router.post('/mock', ctrls.createUsers)
router.put('/final-register/:token', ctrls.finalRegister)
router.post('/login', ctrls.login)
router.get('/current', [verifyAccessToken], ctrls.getCurrent)
router.get('/', [verifyAccessToken, isAdmin], ctrls.getUsers)
router.post('/refreshtoken', ctrls.refreshAccessToken)
router.get('/logout', ctrls.logout)
router.post("/forgot-password", ctrls.forgotPassword)
router.put("/resetpassword", ctrls.resetPassword)
router.put("/address", [verifyAccessToken], ctrls.updateUser)
router.put("/cart", [verifyAccessToken], ctrls.updateCart)
router.put("/current", [verifyAccessToken], uploader.single("avatar"), ctrls.updateUser)
router.delete("/remove/:pid", [verifyAccessToken], ctrls.removeProductInCart)
router.delete("/:uid", [verifyAccessToken, isAdmin], ctrls.deleteUser)
router.put("/wishlist/:pid", [verifyAccessToken], ctrls.updateWishlist)
router.put("/:uid", [verifyAccessToken, isAdmin], ctrls.updateUserByAdmin)

module.exports = router